// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package nas

import (
	"github.com/alice02/nifcloud-sdk-go/nifcloud"
	"github.com/alice02/nifcloud-sdk-go/nifcloud/client"
	"github.com/alice02/nifcloud-sdk-go/nifcloud/client/metadata"
	"github.com/alice02/nifcloud-sdk-go/nifcloud/request"
	"github.com/alice02/nifcloud-sdk-go/nifcloud/signer/v4"
	"github.com/alice02/nifcloud-sdk-go/private/protocol/query"
)

// Nas provides the API operation methods for making requests to
// NIFCLOUD NAS. See this package's package overview docs
// for details on the service.
//
// Nas methods are safe to use concurrently. It is not safe to
// modify mutate any of the struct's properties though.
type Nas struct {
	*client.Client
}

// Used for custom client initialization logic
var initClient func(*client.Client)

// Used for custom request initialization logic
var initRequest func(*request.Request)

// Service information constants
const (
	ServiceName = "nas"       // Service endpoint prefix API calls made to.
	EndpointsID = ServiceName // Service ID for Regions and Endpoints metadata.
)

// New creates a new instance of the Nas client with a session.
// If additional configuration is needed for the client instance use the optional
// nifcloud.Config parameter to add your extra config.
//
// Example:
//     // Create a Nas client from just a session.
//     svc := nas.New(mySession)
//
//     // Create a Nas client with additional configuration
//     svc := nas.New(mySession, nifcloud.NewConfig().WithRegion("us-west-2"))
func New(p client.ConfigProvider, cfgs ...*nifcloud.Config) *Nas {
	c := p.ClientConfig(EndpointsID, cfgs...)
	return newClient(*c.Config, c.Handlers, c.Endpoint, c.SigningRegion, c.SigningName)
}

// newClient creates, initializes and returns a new service client instance.
func newClient(cfg nifcloud.Config, handlers request.Handlers, endpoint, signingRegion, signingName string) *Nas {
	svc := &Nas{
		Client: client.New(
			cfg,
			metadata.ClientInfo{
				ServiceName:   ServiceName,
				SigningName:   signingName,
				SigningRegion: signingRegion,
				Endpoint:      endpoint,
				APIVersion:    "N2016-02-24",
			},
			handlers,
		),
	}

	// Handlers
	svc.Handlers.Sign.PushBackNamed(v4.SignRequestHandler)
	svc.Handlers.Build.PushBackNamed(query.BuildHandler)
	svc.Handlers.Unmarshal.PushBackNamed(query.UnmarshalHandler)
	svc.Handlers.UnmarshalMeta.PushBackNamed(query.UnmarshalMetaHandler)
	svc.Handlers.UnmarshalError.PushBackNamed(query.UnmarshalErrorHandler)

	// Run custom client initialization if present
	if initClient != nil {
		initClient(svc.Client)
	}

	return svc
}

// newRequest creates a new request for a Nas operation and runs any
// custom request initialization.
func (c *Nas) newRequest(op *request.Operation, params, data interface{}) *request.Request {
	req := c.NewRequest(op, params, data)

	// Run custom request initialization if present
	if initRequest != nil {
		initRequest(req)
	}

	return req
}
