// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package script provides the client and types for making API
// requests to NIFCLOUD Script.
//
// See https://docs.aws.amazon.com/goto/WebAPI/script-2015-09-01 for more information on this service.
//
// See script package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/script/
//
// Using the Client
//
// To contact NIFCLOUD Script with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See nifcloud.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/nifcloud/#Config
//
// See the NIFCLOUD Script client Script for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/script/#New
package script
