// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package rdb provides the client and types for making API
// requests to NIFCLOUD RDB.
//
// See https://docs.aws.amazon.com/goto/WebAPI/rdb-2013-05-15N2013-12-16 for more information on this service.
//
// See rdb package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/rdb/
//
// Using the Client
//
// To contact NIFCLOUD RDB with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See nifcloud.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/nifcloud/#Config
//
// See the NIFCLOUD RDB client Rdb for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/rdb/#New
package rdb
